// Mock data for development - replace with Firebase data once seeded
import type { Product, Variant, Review, Order } from '@/types';

export const mockProducts: Product[] = [
  {
    id: 'product-1',
    slug: 'classic-white-thobe',
    sku: 'SKU-product-1',
    titleEn: 'Classic White Thobe',
    titleAr: 'Classic White Thobe',
    subtitleEn: 'Premium cotton blend with elegant drape',
    category: 'THOBE',
    basePrice: 8900, // $89.00
    price: 8900,
    currency: 'USD',
    featured: false,
    tags: [],
    colors: ['White', 'Cream'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeve: 'long',
    defaultImage: { url: '/placeholder.svg', w: 800, h: 1000, altEn: 'Classic White Thobe', altAr: 'Classic White Thobe', sort: 0 },
    descriptionEn: 'Our classic white thobe is crafted from premium cotton blend fabric, offering exceptional comfort and breathability. Perfect for daily wear or special occasions.',
    care: 'Machine wash cold. Hang dry. Iron on low heat.',
    fabric: '65% Cotton, 35% Polyester blend',
    status: 'ACTIVE',
    counts: { variants: 1, activeVariants: 1, totalStock: 24, reviewCount: 0, ratingAvg: 0 },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'product-2',
    slug: 'luxury-black-thobe',
    sku: 'SKU-product-2',
    titleEn: 'Luxury Black Thobe',
    titleAr: 'Luxury Black Thobe',
    subtitleEn: 'Sophisticated evening wear',
    category: 'THOBE',
    basePrice: 12900,
    price: 12900,
    currency: 'USD',
    featured: false,
    tags: [],
    colors: ['Black'],
    sizes: ['M', 'L', 'XL'],
    sleeve: 'long',
    defaultImage: { url: '/placeholder.svg', w: 800, h: 1000, altEn: 'Luxury Black Thobe', altAr: 'Luxury Black Thobe', sort: 0 },
    descriptionEn: 'Elegant black thobe with slim fit design, perfect for formal occasions and evening wear.',
    status: 'ACTIVE',
    counts: { variants: 1, activeVariants: 1, totalStock: 15, reviewCount: 0, ratingAvg: 0 },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'product-3',
    slug: 'traditional-saudi-shemagh',
    sku: 'SKU-product-3',
    titleEn: 'Traditional Saudi Shemagh',
    titleAr: 'Traditional Saudi Shemagh',
    subtitleEn: 'Authentic red and white pattern',
    category: 'SHAAL',
    basePrice: 3900,
    price: 3900,
    currency: 'USD',
    featured: false,
    tags: [],
    colors: ['Red/White'],
    sizes: ['One Size'],
    defaultImage: { url: '/placeholder.svg', w: 800, h: 1000, altEn: 'Traditional Saudi Shemagh', altAr: 'Traditional Saudi Shemagh', sort: 0 },
    descriptionEn: 'Authentic Saudi shemagh with traditional red and white pattern. Made from premium cotton.',
    status: 'ACTIVE',
    counts: { variants: 1, activeVariants: 1, totalStock: 50, reviewCount: 0, ratingAvg: 0 },
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'product-4',
    slug: 'yemeni-shaal-scarf',
    sku: 'SKU-product-4',
    titleEn: 'Yemeni Shaal Scarf',
    titleAr: 'Yemeni Shaal Scarf',
    subtitleEn: 'Hand-woven traditional design',
    category: 'SHAAL',
    basePrice: 4500,
    price: 4500,
    currency: 'USD',
    featured: false,
    tags: [],
    colors: ['Black/White', 'Brown/White'],
    sizes: ['One Size'],
    defaultImage: { url: '/placeholder.svg', w: 800, h: 1000, altEn: 'Yemeni Shaal Scarf', altAr: 'Yemeni Shaal Scarf', sort: 0 },
    descriptionEn: 'Hand-woven Yemeni shaal with intricate traditional patterns.',
    status: 'ACTIVE',
    counts: { variants: 1, activeVariants: 1, totalStock: 30, reviewCount: 0, ratingAvg: 0 },
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'product-5',
    slug: 'egyptian-kufi-cap',
    sku: 'SKU-product-5',
    titleEn: 'Egyptian Kufi Cap',
    titleAr: 'Egyptian Kufi Cap',
    subtitleEn: 'Traditional prayer cap',
    category: 'KUFI',
    basePrice: 1900,
    price: 1900,
    currency: 'USD',
    featured: false,
    tags: [],
    colors: ['White', 'Black', 'Gray'],
    sizes: ['S', 'M', 'L'],
    defaultImage: { url: '/placeholder.svg', w: 800, h: 1000, altEn: 'Egyptian Kufi Cap', altAr: 'Egyptian Kufi Cap', sort: 0 },
    descriptionEn: 'Traditional Egyptian kufi cap, perfect for prayer and daily wear.',
    status: 'ACTIVE',
    counts: { variants: 1, activeVariants: 1, totalStock: 60, reviewCount: 0, ratingAvg: 0 },
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'product-6',
    slug: 'kids-white-thobe',
    sku: 'SKU-product-6',
    titleEn: "Kids' White Thobe",
    titleAr: "Kids' White Thobe",
    subtitleEn: 'Comfortable fit for children',
    category: 'THOBE',
    basePrice: 4900,
    price: 4900,
    currency: 'USD',
    featured: false,
    tags: [],
    colors: ['White'],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    sleeve: 'long',
    defaultImage: { url: '/placeholder.svg', w: 800, h: 1000, altEn: "Kids' White Thobe", altAr: "Kids' White Thobe", sort: 0 },
    descriptionEn: 'Specially designed thobe for children with comfortable fit and durable fabric.',
    status: 'ACTIVE',
    counts: { variants: 1, activeVariants: 1, totalStock: 40, reviewCount: 0, ratingAvg: 0 },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
];

export const mockVariants: Variant[] = mockProducts.flatMap((product) =>
  (product.sizes || ['One Size']).map((size, idx) => ({
    id: `${product.id}-variant-${idx}`,
    productId: product.id,
    productSlug: product.slug,
    productTitleEn: product.titleEn,
    productTitleAr: product.titleAr,
    category: product.category,
    sku: `${product.id}-${size}`,
    size,
    price: product.price || product.basePrice,
    compareAt: undefined,
    stock: Math.floor((product.counts?.totalStock || 0) / ((product.sizes?.length || 1))),
    active: true,
    imageUrl: product.defaultImage?.url,
    createdAt: product.createdAt,
    updatedAt: product.updatedAt,
  }))
);

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    productId: 'product-1',
    rating: 5,
    title: 'Excellent Quality',
    body: 'The fabric is superb and the fit is perfect. Highly recommend!',
    name: 'Ahmed K.',
    approved: true,
    pinnedHome: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'review-2',
    productId: 'product-1',
    rating: 5,
    title: 'Very Comfortable',
    body: 'Wear it all day without any discomfort. Great purchase!',
    name: 'Mohammed A.',
    approved: true,
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'review-3',
    productId: 'product-2',
    rating: 5,
    title: 'Perfect for Events',
    body: 'Wore it to a wedding and received many compliments. The fit is excellent.',
    name: 'Omar S.',
    approved: true,
    pinnedHome: true,
    createdAt: new Date('2024-02-05'),
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    email: 'customer@example.com',
    status: 'PENDING',
    subtotal: 17800,
    shipping: 0,
    tax: 0,
    total: 17800,
    currency: 'USD',
    items: [
      {
        id: 'item-1',
        productId: 'product-1',
        variantId: 'product-1-variant-0',
        title: 'Classic White Thobe',
        sku: 'SKU-product-1-L',
        qty: 2,
        unitPrice: 8900,
        imageUrl: '/placeholder.svg',
        size: 'L',
      },
    ],
    shippingAddress: {
      fullName: 'Ahmed Hassan',
      email: 'customer@example.com',
      address: '123 Main Street',
      city: 'Dearborn',
      state: 'MI',
      zip: '48126',
      country: 'USA',
      phone: '+1 (234) 567-8900',
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];


