// Mock data for development - replace with Firebase data once seeded
import type { Product, Variant, Review, Order } from '@/types';

export const mockProducts: Product[] = [
  {
    id: 'product-1',
    slug: 'classic-white-thobe',
    name: 'Classic White Thobe',
    subtitle: 'Premium cotton blend with elegant drape',
    categoryId: 'thobes',
    price: 8900, // $89.00
    compareAtPrice: 12900,
    colors: ['White', 'Cream'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sleeve: 'long',
    fit: 'classic',
    stock: 24,
    images: ['/placeholder.svg', '/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    descriptionHtml: '<p>Our classic white thobe is crafted from premium cotton blend fabric, offering exceptional comfort and breathability. Perfect for daily wear or special occasions.</p>',
    careHtml: '<p>Machine wash cold. Hang dry. Iron on low heat.</p>',
    fabricHtml: '<p>65% Cotton, 35% Polyester blend</p>',
    badges: ['Best Seller'],
    published: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'product-2',
    slug: 'luxury-black-thobe',
    name: 'Luxury Black Thobe',
    subtitle: 'Sophisticated evening wear',
    categoryId: 'thobes',
    price: 12900,
    colors: ['Black'],
    sizes: ['M', 'L', 'XL'],
    sleeve: 'long',
    fit: 'slim',
    stock: 15,
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    descriptionHtml: '<p>Elegant black thobe with slim fit design, perfect for formal occasions and evening wear.</p>',
    badges: ['New Arrival'],
    published: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'product-3',
    slug: 'traditional-saudi-shemagh',
    name: 'Traditional Saudi Shemagh',
    subtitle: 'Authentic red and white pattern',
    categoryId: 'shemaghs',
    price: 3900,
    colors: ['Red/White'],
    sizes: ['One Size'],
    stock: 50,
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    descriptionHtml: '<p>Authentic Saudi shemagh with traditional red and white pattern. Made from premium cotton.</p>',
    published: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'product-4',
    slug: 'yemeni-shaal-scarf',
    name: 'Yemeni Shaal Scarf',
    subtitle: 'Hand-woven traditional design',
    categoryId: 'shaals',
    price: 4500,
    colors: ['Black/White', 'Brown/White'],
    sizes: ['One Size'],
    stock: 30,
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    descriptionHtml: '<p>Hand-woven Yemeni shaal with intricate traditional patterns.</p>',
    badges: ['Handmade'],
    published: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'product-5',
    slug: 'egyptian-kufi-cap',
    name: 'Egyptian Kufi Cap',
    subtitle: 'Traditional prayer cap',
    categoryId: 'kufis',
    price: 1900,
    colors: ['White', 'Black', 'Gray'],
    sizes: ['S', 'M', 'L'],
    stock: 60,
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    descriptionHtml: '<p>Traditional Egyptian kufi cap, perfect for prayer and daily wear.</p>',
    published: true,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'product-6',
    slug: 'kids-white-thobe',
    name: "Kids' White Thobe",
    subtitle: 'Comfortable fit for children',
    categoryId: 'thobes',
    price: 4900,
    colors: ['White'],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    sleeve: 'long',
    fit: 'kids',
    stock: 40,
    images: ['/placeholder.svg'],
    thumbnail: '/placeholder.svg',
    descriptionHtml: '<p>Specially designed thobe for children with comfortable fit and durable fabric.</p>',
    published: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
];

export const mockVariants: Variant[] = mockProducts.flatMap(product => 
  (product.sizes || ['One Size']).map((size, idx) => ({
    id: `${product.id}-variant-${idx}`,
    productId: product.id,
    productSlug: product.slug,
    productTitleEn: product.name,
    productTitleAr: product.name, // Would be translated
    category: 'THOBE' as const,
    sku: `${product.id}-${size}`,
    size,
    price: product.price,
    compareAt: product.compareAtPrice,
    stock: Math.floor(product.stock / (product.sizes?.length || 1)),
    active: true,
    imageUrl: product.thumbnail,
    createdAt: product.createdAt,
    updatedAt: product.updatedAt,
  }))
);

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    productId: 'product-1',
    rating: 5,
    title: 'Excellent Quality',
    body: 'The fabric is superb and the fit is perfect. Highly recommend!',
    name: 'Ahmed K.',
    approved: true,
    pinnedHome: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'review-2',
    productId: 'product-1',
    rating: 5,
    title: 'Very Comfortable',
    body: 'Wear it all day without any discomfort. Great purchase!',
    name: 'Mohammed A.',
    approved: true,
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'review-3',
    productId: 'product-2',
    rating: 5,
    title: 'Perfect for Events',
    body: 'Wore it to a wedding and received many compliments. The fit is excellent.',
    name: 'Omar S.',
    approved: true,
    pinnedHome: true,
    createdAt: new Date('2024-02-05'),
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    email: 'customer@example.com',
    shippingAddress: {
      fullName: 'Ahmed Hassan',
      address: '123 Main Street',
      city: 'Dearborn',
      state: 'MI',
      zip: '48126',
      country: 'USA',
      phone: '+1 (234) 567-8900',
    },
    items: [
      {
        id: 'item-1',
        productId: 'product-1',
        slug: 'classic-white-thobe',
        name: 'Classic White Thobe',
        price: 8900,
        qty: 2,
        size: 'L',
        image: '/placeholder.svg',
      },
    ],
    subtotal: 17800,
    total: 17800,
    status: 'pending',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
];


